# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command to install dependencies
    - name: Install modules
      run: npm install

    # Runs a set of commands using the runners shell
    - name: Run jest tests with repo secrets as expected (.env) environment variables
      env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_LINK: ${{ secrets.DB_LINK }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
          DB_USER: ${{ secrets.DB_USER }}
          REDIS_IP: ${{ secrets.REDIS_IP }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
      run: npm test

    # Send reports to codecov 
    - name: Send reports to codecov 
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: ./node_modules/.bin/codecov/ --token=CODECOV_TOKEN 
